BUG: declare "gfk" variable before call of terminate() in newton-cg
In _minimize_newtoncg(), the first call to terminate() might occur
before the "gfk" variable has been declared, leading to:

    NameError: free variable 'gfk' referenced before assignment in enclosing scope

This happens for instance if maxiter is negative as demonstrated in
added test case.

Closes #8241.