BLD: replace the #include of libqull_r.h with with this of qhull_ra.h in qhull_misc.c
This is needed for a sucessful build on macOS using
Xcode 12 (Apple's clang 12).

Without it, it errors out with
"error: implicit declaration of function..."

Closes #12860

- `#include <string.h>` is needed for a prototype for strncmp; this include is missing in
  `libqhull_r.h`.
- prototypes for internal functions `qh_setfeasible` and `qh_prepare_output` are missing
  in `libqhull_r.h`